// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { ExecutorKind } from "./ExecutorKind";
import type { UsdMicros } from "./UsdMicros";

export type AiNode = { prompt: string, executor: ExecutorKind, 
/**
 * `executor = host_cli` 时用哪个 CLI（`claude` / `codex` / …）。
 *
 * 保存任务时会对着目标机上报的清单校验一次：让人选一个装都没装的 CLI，
 * 失败会发生在凌晨两点，而不是配置的时候。
 */
cli?: string | null, 
/**
 * 模型 ID。`None` 时由 executor 取默认值（CLI 用 opus，API 用 haiku）。
 */
model?: string | null, effort?: Effort | null, 
/**
 * 要注入上下文的 skill 名字。
 */
skills?: Array<string>, 
/**
 * 允许使用的内置工具。
 *
 * 不给就用执行器的默认白名单（只读）。**这只是第一道闸门**：
 * 真正的约束是工具调用边界上的硬策略，写类工具即使在这里被放进来，
 * 也还要过策略层那一关。
 */
tools?: Array<string>, 
/**
 * agent 循环的最大轮数。防止模型在工具调用里打转。
 */
max_turns?: number | null, 
/**
 * 本节点的成本上限，独立于 run 级预算。
 */
budget_usd?: UsdMicros | null, };
