// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldError } from "./FieldError";

/**
 * 统一错误信封。
 *
 * 刻意不用 RFC 9457 的字段名（`type`/`title`/`detail`/`instance`）：本仓库其它
 * 服务（见 `transfer-app/src/error.rs`）已经用 `{code, message}`，没有客户端
 * 消费那几个额外成员，跨服务一致比贴合规范更有价值。
 */
export type ApiError = { 
/**
 * 稳定的机器可读原因。**这是契约**：新增 code 是兼容变更，
 * 改变已有 code 的触发条件是破坏性变更。
 */
code: string, 
/**
 * 人读文案。不是契约，随时可能改，客户端不要拿它做分支。
 */
message: string, 
/**
 * 与服务端日志关联用，对应 `x-request-id` 响应头。
 */
request_id: string, 
/**
 * 字段级校验失败。**一次返回全部**，不是只报第一个。
 */
details?: Array<FieldError>, };
