// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 超时未决时的默认动作。默认拒绝——审批门的意义就在于「没人点头就不做」。
 */
export type ApprovalTimeout = "deny" | "approve";
