// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalTimeout } from "./ApprovalTimeout";

export type ApprovalNode = { 
/**
 * 审批卡片的标题。
 */
title: string, 
/**
 * 等待人工决策的上限（秒）。
 */
timeout_s: number, on_timeout: ApprovalTimeout, };
