// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/v1/runs/{id}/nodes/{key}/approve`
 */
export type ApprovalDecision = { approved: boolean, reason?: string | null, };
