// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cmp } from "./Cmp";
import type { InputRef } from "./InputRef";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 校验方式。
 */
export type AssertNode = { "mode": "json_schema", schema: JsonValue, } | { "mode": "expression", left: InputRef, cmp: Cmp, right: JsonValue, } | { "mode": "judge", prompt: string, model?: string | null, };
