// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalId } from "./ApprovalId";
import type { RunId } from "./RunId";

/**
 * `POST /internal/policy/await` 的请求：等一条已建好的审批。
 */
export type AwaitApprovalRequest = { run_id: RunId, approval_id: ApprovalId, };
