// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /internal/policy/await` 的响应。
 */
export type AwaitApprovalResponse = { 
/**
 * 还没有结论，调用方应当再问一次。
 */
pending: boolean, 
/**
 * `pending` 为 false 时才有意义。
 */
approved: boolean, reason: string, };
