// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostSelector } from "./HostSelector";

/**
 * `POST /api/v1/commands/check`：先看这条命令在每台机器上会被策略怎么判，不执行。
 */
export type CheckCommand = { 
/**
 * 交给目标机上的 `sh -c`。
 */
command: string, 
/**
 * 在哪些机器上跑：一台、勾选的几台、或者某个 tag 下的全部。不支持中心本机。
 */
targets: HostSelector, };
