// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 比较运算符。刻意不做通用表达式语言：规则要可审计、可静态分析。
 */
export type Cmp = "eq" | "ne" | "lt" | "lte" | "gt" | "gte" | "contains" | "exists" | "not_exists";
