// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostVerdict } from "./HostVerdict";

/**
 * `POST /api/v1/commands/check` 的响应。
 */
export type CommandCheck = { 
/**
 * 按主机名排。
 */
hosts: Array<HostVerdict>, 
/**
 * 被策略拒绝的台数。大于 0 时这条命令不能执行。
 */
denied: number, 
/**
 * 需要人工确认的台数。执行时要带 `confirm: true`。
 */
needs_confirmation: number, };
