// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DagSpec } from "./DagSpec";

/**
 * `POST /api/v1/tasks` —— 需要 `Idempotency-Key` 头。
 */
export type CreateTask = { name: string, description?: string | null, spec: DagSpec, 
/**
 * 要应用的规则 ID/名字。全局规则始终生效，这里只列任务级追加的。
 */
rules?: Array<string>, enabled: boolean, };
