// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { NodeSpec } from "./NodeSpec";
import type { UsdMicros } from "./UsdMicros";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 一个任务版本的完整编排定义。
 */
export type DagSpec = { nodes: Array<NodeSpec>, edges: Array<Edge>, 
/**
 * 触发时可传入的自由参数的 JSON Schema。`None` 表示不接受输入。
 */
input_schema?: JsonValue | null, 
/**
 * 整个 run 的成本上限。超出即熔断，run 落 `budget_exceeded`。
 */
budget_usd?: UsdMicros | null, 
/**
 * 整个 run 的墙钟上限（秒）。
 */
timeout_s?: number | null, };
