// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsdMicros } from "./UsdMicros";

export type DailyBucket = { date: string, 
/**
 * 这一天开始的执行次数，**不含影子执行**。
 */
runs: number, succeeded: number, 
/**
 * 落在失败类终态的次数（failed / timed_out / budget_exceeded / resource_exceeded）。
 */
failed: number, 
/**
 * 这一天的花费，**含影子执行**：影子执行的模型调用一样要钱。
 */
spend_usd: UsdMicros, };
