// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cmp } from "./Cmp";
import type { InputRef } from "./InputRef";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 边的触发条件。默认只在上游成功时放行。
 */
export type EdgeCondition = { "op": "on_success" } | { "op": "on_failure" } | { "op": "always" } | { "op": "expr", left: InputRef, cmp: Cmp, right: JsonValue, };
