// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeCondition } from "./EdgeCondition";
import type { NodeKey } from "./NodeKey";

/**
 * 节点之间的依赖边。
 */
export type Edge = { from: NodeKey, to: NodeKey, when: EdgeCondition, };
