// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 思考深度。对应 Messages API 的 `output_config.effort`。
 */
export type Effort = "low" | "medium" | "high" | "xhigh" | "max";
