// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskId } from "./TaskId";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * `POST /api/v1/rules/evaluate` 的请求：拿一次假想的工具调用试算硬策略。
 *
 * 和真正的工具调用走同一个判决函数，只是**不写事件、不建审批、不记审计**。
 */
export type EvaluatePolicy = { 
/**
 * 工具名，如 `Bash`、`remote_write`。`mcp__ai_task_remote__` 前缀按真实判决的口径归一。
 */
tool: string, 
/**
 * 工具参数，和模型发出的 `tool_input` 同形，必须是 JSON 对象。
 */
input: JsonValue, 
/**
 * 目标主机的 tag。本机执行留空。
 */
host_tags: Array<string>, 
/**
 * 按这个任务挂载的规则和范围来判；不给就只判全局规则。
 */
task_id?: TaskId | null, 
/**
 * 按影子执行来判：写类工具只记录意图、不执行。
 */
dry_run: boolean, };
