// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldError = { 
/**
 * 出错字段的路径，如 `nodes[2].config.prompt`。
 */
field: string, code: string, message: string, };
