// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStatus } from "./HealthStatus";

export type HealthCheck = { name: string, status: HealthStatus, detail?: string | null, latency_ms: number, };
