// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthCheck } from "./HealthCheck";
import type { HealthStatus } from "./HealthStatus";

/**
 * `GET /api/v1/healthz`
 */
export type Health = { status: HealthStatus, version: string, 
/**
 * 各依赖的探测结果。`healthz` 只看进程存活，`readyz` 会填这个。
 */
checks?: Array<HealthCheck>, };
