// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 目标机上找到的一个 AI CLI。
 */
export type HostCli = { name: string, path: string, version?: string | null, };
