// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostId } from "./HostId";

/**
 * 展开步骤落到的一台机器。
 */
export type HostTarget = { host_id: HostId, name: string, };
