// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostId } from "./HostId";
import type { PolicyEffect } from "./PolicyEffect";

/**
 * 一台机器上的策略判决。
 */
export type HostVerdict = { host_id: HostId, host_name: string, effect: PolicyEffect, reason: string, rule_name?: string | null, };
