// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostId } from "./HostId";

/**
 * 节点在哪台机器上执行。
 */
export type HostSelector = { "on": "local" } | { "on": "host", host_id: HostId, } | { "on": "tag", tag: string, };
