// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProbedAgent } from "./ProbedAgent";

/**
 * `POST /api/v1/hosts/{id}/probe` 的响应。
 *
 * **连不上是探测的结论，不是接口错误**：`ok` 为 false、`error` 说明原因，状态码仍是 200。
 */
export type HostProbe = { ok: boolean, error?: string | null, elapsed_ms: number, 
/**
 * 握手拿到的能力快照。`ok` 为 true 时才有。
 */
agent?: ProbedAgent | null, };
