// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKey } from "./NodeKey";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 节点取值的来源。
 */
export type InputRef = { "from": "node", node: NodeKey, path: string, } | { "from": "run_input", path: string, } | { "from": "map_item" } | { "from": "literal", value: JsonValue, };
