// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputRef } from "./InputRef";
import type { NodeSpec } from "./NodeSpec";

export type MapNode = { 
/**
 * 要遍历的数组。取值不是数组时节点直接失败。
 */
over: InputRef, 
/**
 * 每个元素实例化一份。模板里用 [`InputRef::MapItem`] 引用当前元素。
 */
template: NodeSpec, max_parallel: number, 
/**
 * 元素数上限。**必填且有默认值**：`over` 来自 AI 输出，
 * 一个失控的数组能瞬间放大成几千个 run 节点。
 */
max_items: number, };
