// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 定时器错过触发点后的补偿策略（服务停过一段时间）。
 */
export type MisfirePolicy = "skip" | "fire_once" | "fire_all";
