// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个节点实例的状态。
 */
export type NodeStatus = "pending" | "ready" | "running" | "awaiting_approval" | "succeeded" | "failed" | "skipped" | "cancelled";
