// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DAG 内的节点标识，由用户在编排时指定，在一个任务版本内唯一。
 *
 * 不用 UUID：节点 key 会出现在 `inputs` 的 JSONPath 引用里，要人可读、可手写。
 */
export type NodeKey = string;
