// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiNode } from "./AiNode";
import type { ApprovalNode } from "./ApprovalNode";
import type { AssertNode } from "./AssertNode";
import type { MapNode } from "./MapNode";
import type { ShellNode } from "./ShellNode";

/**
 * 节点类型与它各自的配置。
 *
 * 内部 tag（`kind`）而不是嵌套对象：JSON 更扁平，TS 侧是天然的可辨识联合。
 */
export type NodeConfig = { "kind": "ai" } & AiNode | { "kind": "shell" } & ShellNode | { "kind": "assert" } & AssertNode | { "kind": "approval" } & ApprovalNode | { "kind": "map" } & MapNode;
