// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostSelector } from "./HostSelector";
import type { InputRef } from "./InputRef";
import type { NodeConfig } from "./NodeConfig";
import type { NodeKey } from "./NodeKey";
import type { OnFailure } from "./OnFailure";
import type { ResourceLimits } from "./ResourceLimits";
import type { RetryPolicy } from "./RetryPolicy";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * DAG 里的一个节点。
 */
export type NodeSpec = { key: NodeKey, 
/**
 * 展示名。为空时界面回退到 `key`。
 */
name?: string | null, 
/**
 * 节点类型与配置。
 *
 * 刻意**不用** `#[serde(flatten)]` 把 `kind` 提到顶层：serde 的 `flatten`
 * 与 `deny_unknown_fields` 互斥，一旦 flatten 就必须放弃整个 spec 的字段
 * 拼写检查。这是人手写的 YAML，「配了但没生效」是最坏的失败模式，
 * 换一层嵌套换全量拼写检查是划算的。
 */
config: NodeConfig, 
/**
 * 节点输入：名字 → 取值来源。名字会以变量形式出现在 prompt / command 里。
 */
inputs?: { [key in string]: InputRef }, 
/**
 * 输出契约。校验不过时按 [`RetryPolicy::feed_error_to_model`] 决定是否回喂重试。
 */
output_schema?: JsonValue | null, retry: RetryPolicy, on_failure: OnFailure, 
/**
 * 单个节点的墙钟上限（秒）。
 */
timeout_s?: number | null, 
/**
 * 在哪台机器上执行。`None` 等同 [`HostSelector::Local`]。
 */
host?: HostSelector | null, 
/**
 * 资源上限。
 *
 * 只在目标机能强制时才真的生效（需要 cgroup v2 + systemd）；
 * 降级的机器上会记账但不设限，事件日志里会明确写出来——
 * 谎称限额在生效比不限更糟。
 */
limits?: ResourceLimits | null, };
