// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 成功和失败各几次。失败指 failed / timed_out / budget_exceeded / resource_exceeded。
 */
export type OutcomeCounts = { succeeded: number, failed: number, };
