// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/v1/overview/tasks` 的查询参数。
 */
export type OverviewTasksQuery = { 
/**
 * 看最近几小时，1–720，默认 168（7 天）。
 */
window_hours?: number | null, 
/**
 * 最多几个任务，1–20，默认 5。
 */
limit?: number | null, };
