// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskHealth } from "./TaskHealth";

/**
 * 窗口内失败最多的几个任务。只列有失败的，失败次数多的在前；不分页，这是一份排行。
 */
export type OverviewTasks = { window_hours: number, items: Array<TaskHealth>, };
