// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyBucket } from "./DailyBucket";

/**
 * 每天的执行结果，旧的在前，没有执行的日子也有一行（全是 0）。
 */
export type OverviewDaily = { 
/**
 * 分桶用的时区。`days[].date` 是这个时区的日历日。
 */
timezone: string, days: Array<DailyBucket>, };
