// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/v1/overview/daily` 的查询参数。
 */
export type OverviewDailyQuery = { 
/**
 * 看最近几天（含今天），1–90，默认 14。
 */
days?: number | null, 
/**
 * 按哪个时区的日历日分桶，IANA 名，默认 `Asia/Shanghai`。
 */
timezone?: string | null, };
