// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/v1/overview` 的查询参数。
 */
export type OverviewQuery = { 
/**
 * 统计窗口，小时。默认 24，上限 720（30 天）。
 */
window_hours?: number | null, };
