// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverviewRun } from "./OverviewRun";
import type { OverviewStats } from "./OverviewStats";
import type { UpcomingFire } from "./UpcomingFire";

/**
 * 首页那一屏要的全部数字，一次算完。
 *
 * **这个接口首先是个正确性修复，不只是少发几个请求。**
 * 之前首页是拉最近 200 条 run 回浏览器里算 24 小时的次数、失败数和花费——
 * 实例一忙，第 201 条之后的就静静地不算了，而界面上那三个数字看不出自己是错的。
 * 窗口聚合只能在数据库里做。
 */
export type Overview = { stats: OverviewStats, 
/**
 * 正在跑和排队中的，最近的在前。
 */
live: Array<OverviewRun>, 
/**
 * 最近结束的。
 */
recent: Array<OverviewRun>, 
/**
 * 接下来会自己触发的定时。
 */
upcoming: Array<UpcomingFire>, };
