// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutcomeCounts } from "./OutcomeCounts";
import type { UsdMicros } from "./UsdMicros";

/**
 * 首页顶部那一排指标。
 */
export type OverviewStats = { 
/**
 * 下面几个窗口内的统计按这个小时数算。回显出来，免得客户端自己猜。
 */
window_hours: number, 
/**
 * 窗口内的 run 总数。
 */
runs: number, 
/**
 * 窗口内落在失败类终态（failed / timed_out / budget_exceeded / resource_exceeded）的。
 */
failed: number, 
/**
 * 窗口内的模型花费合计。
 */
spend_usd: UsdMicros, 
/**
 * 当前在跑的（不受窗口限制）。
 */
running: number, 
/**
 * 当前排队的（不受窗口限制）。
 */
queued: number, 
/**
 * 当前待决的审批（不受窗口限制）。
 */
pending_approvals: number, 
/**
 * 任务总数。
 */
tasks: number, 
/**
 * 窗口内**不含影子执行**的结局。成功率按它算：影子执行是在试提示词，
 * 它失败了不代表任务出了问题。上面的 `runs` / `failed` 含影子执行，语义不变。
 */
outcomes: OutcomeCounts, };
