// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunId } from "./RunId";
import type { RunStatus } from "./RunStatus";
import type { TaskId } from "./TaskId";
import type { TriggerKind } from "./TriggerKind";
import type { UsdMicros } from "./UsdMicros";

/**
 * 首页列表里的一行。
 *
 * 比 [`RunSummary`] 少几个字段、多一个 `task_name`：首页每一行都要显示任务名，
 * 而客户端为此再拉一遍任务表、逐行 `find` 是没必要的。
 */
export type OverviewRun = { id: RunId, task_id: TaskId, task_name: string, status: RunStatus, trigger: TriggerKind, dry_run: boolean, created_at: string, started_at?: string | null, finished_at?: string | null, cost_usd: UsdMicros, error?: string | null, };
