// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 列表接口的分页参数。
 */
export type PageQuery = { 
/**
 * 上一页返回的 `next_cursor`。
 */
cursor?: string | null, 
/**
 * 每页条数。服务端封顶 [`PageQuery::MAX_LIMIT`]，超出直接按上限截断。
 */
limit?: number | null, };
