// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 游标分页的一页结果。
 */
export type Page<T> = { items: Array<T>, 
/**
 * 下一页的游标。`None` 表示到底了。
 *
 * 对客户端不透明：里面编码的是 `(created_at, id)`，格式随时可能变。
 */
next_cursor?: string | null, };
