// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyDecidedBy } from "./PolicyDecidedBy";
import type { PolicyEffect } from "./PolicyEffect";
import type { RuleId } from "./RuleId";

/**
 * `POST /api/v1/rules/evaluate` 的响应。
 */
export type PolicyEvaluation = { 
/**
 * 最终结论。
 */
effect: PolicyEffect, 
/**
 * 策略本身的结论。和 `effect` 不同，说明是影子执行把它改成了拒绝。
 */
policy_effect: PolicyEffect, decided_by: PolicyDecidedBy, rule_id?: RuleId | null, rule_name?: string | null, 
/**
 * 回给模型的那句话。
 */
reason: string, 
/**
 * 实际拿去匹配的工具名（归一之后）。
 */
tool: string, 
/**
 * 参与判决的规则条数：已启用的全局规则，加上任务挂载的。
 */
considered: number, };
