// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 结论是谁给出的。客户端要容忍以后新增的取值。
 */
export type PolicyDecidedBy = "rule" | "default" | "invalid_rules";
