// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalId } from "./ApprovalId";

/**
 * `POST /internal/policy/decide` 的响应。
 */
export type PolicyResponse = { 
/**
 * `ask` 只会作为中间态出现在事件日志里；这个接口在人工决策完成后
 * 才返回，所以这里只会是 `allow` 或 `deny`。
 */
allowed: boolean, 
/**
 * 拒绝原因。会作为 `tool_result` 回给模型，让它自己调整，
 * 而不是把调用挂死或直接失败。
 */
reason: string, rule_id?: string | null, 
/**
 * 影子执行下为 true：调用方应当记录意图但不真的执行。
 */
dry_run: boolean, 
/**
 * 命中 `ask`：已建好审批，调用方应当轮询 `/internal/policy/await`
 * 直到有结论或者自己的截止时间到。
 *
 * **不用一个长请求把结论等回来**：那样 hook 的超时必须放大到审批窗口那么长，
 * 于是服务端一旦卡住，每次工具调用都要挂十分钟才失败，而不是二十秒内
 * 快速失败关门。轮询让每个请求都是短的，超时语义不用动。
 */
pending_approval_id?: ApprovalId | null, };
