// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostId } from "./HostId";
import type { RunId } from "./RunId";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * `POST /internal/policy/decide` 的请求。
 *
 * 调用方是 `ai-task-mcp` 的远端工具代理和 Claude Code 的 `PreToolUse` hook，
 * **不对外暴露**。工具调用在这个接口返回前是阻塞的。
 */
export type PolicyRequest = { run_id: RunId, node_key: string, tool_use_id: string, tool: string, input: JsonValue, 
/**
 * 动作的目标主机。`None` 表示中心节点本机。
 */
host_id?: HostId | null, };
