// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostCli } from "./HostCli";

/**
 * 目标机上 agent 自报的能力。
 */
export type ProbedAgent = { hostname: string, arch: string, agent_version: string, 
/**
 * 这次是不是重新投送了 agent 二进制。
 */
uploaded: boolean, 
/**
 * 资源归因档位：`systemd`（能设上限）/ `proc`（只能记账）/ `none`。
 */
cgroup_mode: string, 
/**
 * 没到 `systemd` 档的原因。
 */
cgroup_detail?: string | null, ai_clis: Array<HostCli>, };
