// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunId } from "./RunId";
import type { RunStatus } from "./RunStatus";

/**
 * 一次 run 最少的那点信息：够画一个色块，点进去能跳到它。
 */
export type RecentRun = { id: RunId, status: RunStatus, 
/**
 * 影子执行单独标出来：它是用来试提示词的，失败了不代表任务本身不稳。
 */
dry_run: boolean, created_at: string, };
