// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /internal/remote/call` 的响应。
 *
 * **策略拒绝不是 HTTP 错误**：它是一个模型必须看见并据此调整的正常结果。
 * 返回 4xx 会让 MCP 客户端把它当成传输故障，模型只会原样重试。
 */
export type RemoteCallResponse = { 
/**
 * 动作是否真的执行了。被策略拒绝、或影子执行下，这里是 false。
 */
executed: boolean, 
/**
 * 给模型看的正文：执行结果，或者被拒的原因。
 */
content: string, 
/**
 * 命令退出码。非 `remote_bash` 或未执行时为 `None`。
 */
exit_code?: number | null, rule_id?: string | null, };
