// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 允许在远端做的事。刻意只有这四样。
 */
export type RemoteAction = { "tool": "remote_bash", command: string, working_dir?: string | null, timeout_s?: number | null, } | { "tool": "remote_read", path: string, } | { "tool": "remote_write", path: string, content: string, } | { "tool": "remote_glob", pattern: string, };
