// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteAction } from "./RemoteAction";
import type { RunId } from "./RunId";

/**
 * `POST /internal/remote/call` 的请求。
 *
 * 每个远端动作都必须经过这个接口——**这是策略无法被绕过的原因**：
 * MCP 代理进程里没有 SSH 凭据，它除了打这个接口没有别的路。
 */
export type RemoteCallRequest = { run_id: RunId, node_key: string, 
/**
 * 模型这次调用的 id。判决和结果都挂在它上面，审计时能对上。
 */
tool_use_id: string, 
/**
 * 目标主机。**由中心从任务定义里取，不接受调用方指定**——
 * 否则模型可以自己换一台没有 prod tag 的机器来绕开策略。
 */
action: RemoteAction, };
