// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 节点执行的资源上限。
 */
export type ResourceLimits = { 
/**
 * 内存上限（MiB）。超出由内核直接 kill，run 落 `resource_exceeded`。
 */
memory_mib?: number | null, 
/**
 * CPU 配额，百分比。200 表示最多用满两个核。
 */
cpu_percent?: number | null, 
/**
 * 进程数上限。挡住 fork 炸弹。
 */
pids_max?: number | null, };
