// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 节点重试策略。
 */
export type RetryPolicy = { 
/**
 * 含首次在内的总尝试次数。1 表示不重试。
 */
max_attempts: number, backoff_ms: number, backoff_factor: number, 
/**
 * 把上次的失败原因（含 `output_schema` 的校验错误）作为下一轮输入回喂给模型。
 *
 * 这是「节点契约化」的执行点：让 AI 看见自己错在哪，而不是原样重来。
 */
feed_error_to_model: boolean, };
