// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostSelector } from "./HostSelector";

/**
 * `POST /api/v1/commands`：在几台机器上各跑一次，返回新建的 run。需要 `Idempotency-Key`。
 *
 * 和 check 同一套判法，执行时会再判一次：有任何一台被策略拒绝就整体不执行；
 * 有需要人工确认的，必须带 `confirm: true`。
 */
export type RunCommand = { command: string, targets: HostSelector, 
/**
 * 单台机器上的超时，1–3600 秒，默认 300。
 */
timeout_s?: number | null, 
/**
 * 看过需要人工确认的那些机器，确认要跑。
 */
confirm: boolean, };
