// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunId } from "./RunId";
import type { RunStatus } from "./RunStatus";
import type { ScheduleId } from "./ScheduleId";
import type { TaskId } from "./TaskId";
import type { TaskVersionId } from "./TaskVersionId";
import type { TriggerKind } from "./TriggerKind";
import type { UsdMicros } from "./UsdMicros";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * `GET /api/v1/runs/{id}` —— 一次执行的全部元信息。
 *
 * 比列表多出来的都是详情页才用得上的：输入（重跑要原样带上）、输出（结论）、
 * 版本号（编排图要画**这次执行用的那一版**，不是任务现在的样子）、谁触发的。
 * 是 `RunSummary` 的超集，只多不少。
 */
export type RunDetail = { task_name: string, 
/**
 * 这次执行绑定的版本号。
 */
version_no: number, 
/**
 * 任务**现在**的版本号。和 `version_no` 不同，说明任务在这次执行之后被改过。
 */
current_version_no: number, inputs?: JsonValue | null, 
/**
 * run 的最终输出：拓扑序里最后一个成功节点的输出。
 */
output?: JsonValue | null, compare_to?: RunId | null, 
/**
 * 驱动这次执行的 claude CLI 版本。
 */
cli_version?: string | null, 
/**
 * 手动触发的人（显示名）。定时触发、没开认证时没有。
 */
triggered_by?: string | null, 
/**
 * 定时触发时是哪条定时。
 */
schedule_id?: ScheduleId | null, id: RunId, task_id: TaskId, task_version_id: TaskVersionId, status: RunStatus, trigger: TriggerKind, dry_run: boolean, created_at: string, started_at?: string | null, finished_at?: string | null, cost_usd: UsdMicros, 
/**
 * 失败原因。只在终态且非成功时有值。
 *
 * 加这个字段是为了让轮询 summary 的客户端不必为了知道"为什么失败"
 * 去拉整条事件流。新增可选字段是兼容变更。
 */
error?: string | null, 
/**
 * 事件日志的最大 seq。SSE 客户端用它判断自己落后多少。
 */
max_seq: number, };
