// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKey } from "./NodeKey";
import type { RunEventBody } from "./RunEventBody";
import type { RunId } from "./RunId";

/**
 * 事件日志里的一条记录。
 *
 * 字段与 `run_events` 表一一对应：`(run_id, seq)` 是主键，`body` 落在 `payload`
 * 这个 jsonb 列里，`kind` 另外冗余成一列供过滤用。
 */
export type RunEvent = { run_id: RunId, 
/**
 * run 内单调递增，从 1 开始。
 *
 * 由该 run 的单写者任务分配，不是全局序列——没有跨 run 的竞争点。
 * SSE 的 `Last-Event-ID` 直接用它做断点续传。
 */
seq: number, ts: string, 
/**
 * 事件归属的节点。run 级事件为 `None`。
 */
node_key?: NodeKey | null, body: RunEventBody, };
