// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalId } from "./ApprovalId";
import type { HostId } from "./HostId";
import type { LogLevel } from "./LogLevel";
import type { NodeStatus } from "./NodeStatus";
import type { PolicyEffect } from "./PolicyEffect";
import type { RuleId } from "./RuleId";
import type { RunId } from "./RunId";
import type { RunStatus } from "./RunStatus";
import type { TaskVersionId } from "./TaskVersionId";
import type { TriggerKind } from "./TriggerKind";
import type { UsdMicros } from "./UsdMicros";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 事件负载。
 *
 * **新增 variant 是兼容变更，客户端必须容忍未知 `kind`。** 前端对未识别的事件
 * 应当降级显示为一行原始 JSON，而不是崩溃或静默丢弃。
 */
export type RunEventBody = { "kind": "run_queued", task_version_id: TaskVersionId, trigger: TriggerKind, 
/**
 * 触发时传入的参数。
 */
inputs?: JsonValue | null, 
/**
 * 影子执行：所有副作用工具只记录意图不执行。
 */
dry_run: boolean, } | { "kind": "run_started", worker: string, } | { "kind": "run_finished", status: RunStatus, error?: string | null, 
/**
 * run 全程累计成本。
 */
cost_usd: UsdMicros, } | { "kind": "node_ready" } | { "kind": "node_started", attempt: number, 
/**
 * `None` 表示在中心节点本机执行。
 */
host_id?: HostId | null, } | { "kind": "node_finished", attempt: number, status: NodeStatus, output?: JsonValue | null, error?: string | null, } | { "kind": "node_retrying", attempt: number, delay_ms: number, reason: string, 
/**
 * 是否把 `reason` 回喂给模型（节点契约化的执行点）。
 */
feeding_error_to_model: boolean, } | { "kind": "node_skipped", reason: string, } | { "kind": "drift_detected", 
/**
 * 拿来比较的基线 run。
 */
baseline_run_id: RunId, 
/**
 * 有差异的字段路径，最多列前几条。完整 diff 走 `/runs/{id}/drift`。
 */
changed_paths: Array<string>, } | { "kind": "resource_degraded", 
/**
 * `proc` 或 `none`。`systemd` 不会发这条事件。
 */
mode: string, 
/**
 * 降级的原因，直接来自目标机的探测结果。
 */
detail?: string | null, } | { "kind": "map_expanded", count: number, 
/**
 * 上游数组的真实长度。被 `max_items` 截断时会大于 `count`。
 */
available: number, } | { "kind": "agent_turn_started", turn: number, } | { "kind": "agent_thinking", text: string, } | { "kind": "agent_text", text: string, } | { "kind": "tool_requested", tool_use_id: string, tool: string, input: JsonValue, } | { "kind": "policy_decided", tool_use_id: string, effect: PolicyEffect, 
/**
 * 命中的规则。没有规则命中（走默认策略）时为 `None`。
 */
rule_id?: RuleId | null, reason: string, } | { "kind": "tool_completed", tool_use_id: string, ok: boolean, output_preview: string, duration_ms: number, } | { "kind": "usage", model: string, input_tokens: number, output_tokens: number, cache_read_tokens: number, cache_creation_tokens: number, cost_usd: UsdMicros, } | { "kind": "approval_requested", approval_id: ApprovalId, title: string, 
/**
 * 结构化的意图：要跑的命令、要改的文件、影响的主机。
 * 审批卡片渲染的是它，不是一段自然语言。
 */
intent: JsonValue, expires_at: string, } | { "kind": "approval_decided", approval_id: ApprovalId, approved: boolean, 
/**
 * 超时自动决策时为 `None`。
 */
decided_by?: string | null, reason?: string | null, } | { "kind": "log", level: LogLevel, message: string, };
