// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskId } from "./TaskId";

/**
 * `GET /api/v1/runs` 的查询参数。服务端直接按这个类型解析，所以它就是契约本身。
 *
 * 多选用**逗号分隔**（`status=failed,timed_out`），不用重复的键：查询串的解析
 * 不认重复键。认不出的值整个请求 422——拼错一个状态名不能悄悄变成「不过滤」。
 * 未声明的参数会被拒绝而不是忽略，理由同上。
 */
export type RunFilter = { task_id?: TaskId | null, 
/**
 * 逗号分隔的 [`RunStatus`]。
 */
status?: string | null, 
/**
 * 逗号分隔的 [`TriggerKind`]。
 */
trigger?: string | null, 
/**
 * 只要这个时刻（含）之后创建的，RFC 3339。
 */
since?: string | null, 
/**
 * 上一页的 `next_cursor`。
 */
cursor?: string | null, 
/**
 * 每页条数，1–200，默认 50。
 */
limit?: number | null, };
