// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunStatus } from "./RunStatus";
import type { TaskId } from "./TaskId";
import type { TriggerKind } from "./TriggerKind";

/**
 * `GET /api/v1/runs` 的过滤条件。
 *
 * 未声明的查询参数会被拒绝而不是忽略——静默忽略会把一个拼写错误变成「返回全部」。
 */
export type RunFilter = { task_id?: TaskId | null, status?: Array<RunStatus>, trigger?: TriggerKind | null, since?: string | null, };
