// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunId } from "./RunId";
import type { RunStatus } from "./RunStatus";
import type { TaskId } from "./TaskId";
import type { TaskVersionId } from "./TaskVersionId";
import type { TriggerKind } from "./TriggerKind";
import type { UsdMicros } from "./UsdMicros";

export type RunSummary = { id: RunId, task_id: TaskId, task_version_id: TaskVersionId, status: RunStatus, trigger: TriggerKind, dry_run: boolean, created_at: string, started_at?: string | null, finished_at?: string | null, cost_usd: UsdMicros, 
/**
 * 失败原因。只在终态且非成功时有值。
 *
 * 加这个字段是为了让轮询 summary 的客户端不必为了知道"为什么失败"
 * 去拉整条事件流。新增可选字段是兼容变更。
 */
error?: string | null, 
/**
 * 事件日志的最大 seq。SSE 客户端用它判断自己落后多少。
 */
max_seq: number, };
