// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * run 的终态/进行态。
 */
export type RunStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled" | "timed_out" | "budget_exceeded" | "resource_exceeded";
