// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/v1/schedules/preview` 的查询参数。
 *
 * 编辑定时时边敲边看：表达式写没写对，看接下来几次在什么时候最直接。
 */
export type SchedulePreviewQuery = { 
/**
 * 5 段（分 时 日 月 周）或 6 段（秒 分 时 日 月 周）。
 */
cron: string, 
/**
 * IANA 时区名，如 `Asia/Shanghai`。
 */
timezone: string, 
/**
 * 要看接下来几次，1–10，默认 5。
 */
count?: number | null, };
