// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScheduleFire = { at: string, 
/**
 * 按该时区的本地时间，形如 `2026-09-25 02:00:00 CST`。
 */
local: string, };
