// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduleFire } from "./ScheduleFire";

/**
 * 接下来几次触发。表达式或时区不合法时接口返回 422，字段是 `cron` / `timezone`。
 */
export type SchedulePreview = { fires: Array<ScheduleFire>, };
