// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MisfirePolicy } from "./MisfirePolicy";
import type { OverlapPolicy } from "./OverlapPolicy";
import type { ScheduleId } from "./ScheduleId";
import type { TaskId } from "./TaskId";

export type Schedule = { id: ScheduleId, task_id: TaskId, cron: string, 
/**
 * IANA 时区名，如 `Asia/Shanghai`。DST 的跳过/重复时刻由它决定。
 */
timezone: string, misfire: MisfirePolicy, overlap: OverlapPolicy, 
/**
 * 触发抖动上限（秒），避免整点惊群。
 */
jitter_s: number, enabled: boolean, 
/**
 * 下一次触发时刻。调度器就是按这个字段领取的。
 */
next_fire_at?: string | null, };
