// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 确定性命令。
 *
 * 命令由**操作者**写在编排里，不是模型生成的，所以不过工具调用策略层
 * （那一层管的是模型的自由裁量）。约束它的是节点上的 `limits` 和 `host`：
 * 跑在哪台机器上、能用多少资源。
 */
export type ShellNode = { 
/**
 * 交给 `sh -c` 的命令行。注意 Debian/Ubuntu 上那是 dash 不是 bash。
 */
command: string, working_dir?: string | null, };
