// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillId } from "./SkillId";

/**
 * `GET /api/v1/skills/{name}`：一个技能的最新版全文。
 *
 * ETag 是这一版的 `id`：每次修改都会插一个新版本行，`id` 随之变化。
 */
export type SkillDetail = { 
/**
 * 这一版的 id，也是 `ETag`。
 */
id: SkillId, name: string, version: string, 
/**
 * 渐进式披露时模型只看得到这一句。
 */
description: string, body: string, 
/**
 * 附带文件：相对路径 → 内容。
 */
files: { [key in string]: string }, 
/**
 * 正文和附件的指纹，不含描述。
 */
content_hash: string, created_at: string, 
/**
 * 一共有几个版本。
 */
versions: number, 
/**
 * 当前版本引用了它的任务名（含 map 节点的模板）。删除前要先摘掉。
 */
used_by: Array<string>, };
