// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunSummary } from "./RunSummary";
import type { TaskId } from "./TaskId";
import type { TaskVersionId } from "./TaskVersionId";

export type TaskSummary = { id: TaskId, name: string, description?: string | null, 
/**
 * 当前生效的版本。run 绑定的是版本快照，不是任务本身。
 */
current_version_id: TaskVersionId, enabled: boolean, created_at: string, updated_at: string, 
/**
 * 乐观锁版本号，同时作为 `ETag` 的取值。
 */
version: number, 
/**
 * 最近一次 run 的状态，列表页直接展示，省一次查询。
 */
last_run?: RunSummary | null, };
