// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DagSpec } from "./DagSpec";
import type { TaskId } from "./TaskId";

/**
 * `GET /api/v1/tasks/{id}/versions/{no}` —— 一个版本的编排快照。版本不可变。
 */
export type TaskVersion = { task_id: TaskId, version_no: number, spec: DagSpec, 
/**
 * 这个版本额外挂的规则名。全局规则不在这里。
 */
rules?: Array<string>, created_at: string, };
