// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DagSpec } from "./DagSpec";
import type { RunSummary } from "./RunSummary";
import type { TaskId } from "./TaskId";
import type { TaskVersionId } from "./TaskVersionId";

/**
 * `GET /api/v1/tasks/{id}` —— 带上当前版本的完整编排定义。
 *
 * 列表接口不返回 `spec`：一份 DAG 可能有几十个节点，列表页用不上却要传，
 * 白白拖慢首屏。
 */
export type TaskDetail = { spec: DagSpec, 
/**
 * 这个任务额外应用的规则名。全局规则不在这里。
 */
rules?: Array<string>, 
/**
 * 定义快照的版本号，从 1 开始。
 */
version_no: number, id: TaskId, name: string, description?: string | null, 
/**
 * 当前生效的版本。run 绑定的是版本快照，不是任务本身。
 */
current_version_id: TaskVersionId, enabled: boolean, created_at: string, updated_at: string, 
/**
 * 乐观锁版本号，同时作为 `ETag` 的取值。
 */
version: number, 
/**
 * 最近一次 run 的状态，列表页直接展示，省一次查询。
 */
last_run?: RunSummary | null, };
