// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunId } from "./RunId";
import type { RunStatus } from "./RunStatus";
import type { TaskId } from "./TaskId";
import type { UsdMicros } from "./UsdMicros";

/**
 * 一个任务在窗口内的表现。**不含影子执行。**
 */
export type TaskHealth = { task_id: TaskId, task_name: string, runs: number, failed: number, spend_usd: UsdMicros, 
/**
 * 窗口内最近一次执行。
 */
last_run_id: RunId, last_status: RunStatus, last_run_at: string, last_failed_at: string, 
/**
 * 最近一次失败的原因，最多 200 个字符。
 */
last_error?: string | null, };
