// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunId } from "./RunId";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * `POST /api/v1/tasks/{id}/runs` —— 需要 `Idempotency-Key` 头，返回 202。
 */
export type TriggerRun = { 
/**
 * 传给 DAG 的自由参数，按 [`DagSpec::input_schema`] 校验。
 */
inputs?: JsonValue | null, 
/**
 * 影子执行：所有副作用工具只记录意图不执行。
 */
dry_run: boolean, 
/**
 * 与哪个基线 run 做结构化 diff。配合 `dry_run` 用于换 prompt / 换模型前的验证。
 */
compare_to?: RunId | null, };
