// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * run 的触发来源。
 */
export type TriggerKind = "manual" | "schedule" | "api" | "parent";
