// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduleId } from "./ScheduleId";
import type { TaskId } from "./TaskId";

/**
 * 接下来会自己响的一个定时。
 */
export type UpcomingFire = { schedule_id: ScheduleId, task_id: TaskId, task_name: string, cron: string, next_fire_at: string, };
