// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/v1/skills/{name}`：改一个技能。
 *
 * 内容（描述、正文、附件）变了才插新版本行；和最新版一模一样时什么都不做。
 * 带 `If-Match` 就能挡住并发修改（412）；不带按"不在乎并发"处理，和任务一致。
 */
export type UpdateSkill = { 
/**
 * 新版本号，不能和这个技能用过的任何版本重复。
 */
version: string, description: string, body: string, files: { [key in string]: string }, };
