// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DagSpec } from "./DagSpec";

/**
 * `PUT /api/v1/tasks/{id}` —— 需要 `If-Match` 头，命中即产生新版本。
 *
 * 语义是整体替换（PUT），不是字段合并（PATCH）。
 */
export type UpdateTask = { name: string, description?: string | null, spec: DagSpec, rules?: Array<string>, enabled: boolean, };
